/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author Cauã
 */


import java.util.Random;
import javax.swing.JOptionPane; //biblioteca com telas prontas

public class GenioAdvinhador extends javax.swing.JFrame {

    /**
     * Creates new form GenioAdvinhador
     */
    public GenioAdvinhador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumEscolhido = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblResposta = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        Palpitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResposta.setBackground(new java.awt.Color(0, 0, 0));
        lblResposta.setText("ADVINHE UM NUMERO DE 0 A 5");
        jPanel1.add(lblResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 160));
        lblResposta.getAccessibleContext().setAccessibleName("lblResposta");

        lblBalao.setForeground(new java.awt.Color(0, 0, 0));
        lblBalao.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\pr03cauagomes\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\BALAOSEMFUNDO00.png")); // NOI18N
        jPanel1.add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -10, 280, 230));

        lblGenio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\pr03cauagomes\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\akinatorimagem.jpg")); // NOI18N
        jPanel1.add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 420));

        Palpitar.setText("PALPITE");
        Palpitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalpitarActionPerformed(evt);
            }
        });
        jPanel1.add(Palpitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 84, -1));
        Palpitar.getAccessibleContext().setAccessibleName("btnPalpite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(445, 445, 445))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NumEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1767, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(NumEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1045, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(403, 403, 403))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumEscolhido.getAccessibleContext().setAccessibleName("spnNumEscolhido");

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void PalpitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalpitarActionPerformed
// TODO add your handling code here:
         Random random  = new  Random();
         int NumEsco = (Integer)NumEscolhido.getValue(); // pega o valor do spinner
        
        if( NumEsco >= 0  && NumEsco <= 5 ){ // se estiver entre os valores corretos
        
         int numAleatorio = random.nextInt(6); // pega um numero aleatorio de 0 a 5
          
        if(NumEsco == numAleatorio){ // se acertar a resposta
            lblResposta.setText("PARABENS!! "+ NumEsco +" ERA A RESPOSTA");
        }else{ // se nao acertar
            lblResposta.setText("ERROU!!! "+ numAleatorio +" ERA A RESPOSTA");
        }
        }else{
               JOptionPane.showMessageDialog(null,"ESSE NUMERO NAO ESTA ENTRE 0 E 5","ERROR",JOptionPane.ERROR_MESSAGE);//mensagem de erro usando telas prontas da biblioteca
        }
    }//GEN-LAST:event_PalpitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenioAdvinhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenioAdvinhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenioAdvinhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenioAdvinhador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenioAdvinhador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner NumEscolhido;
    private javax.swing.JButton Palpitar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblResposta;
    // End of variables declaration//GEN-END:variables
}
