/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

/**
 *
 * @author Cauã
 */
import java.time.Year;
public class calculadorawingjava extends javax.swing.JFrame {

    /**
     * Creates new form calculadorawingjava
     */
   
    public calculadorawingjava() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*   @SuppressWarnings("unchecked")*/   @SuppressWarnings("unchecked")
                      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblIdade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        pessoaimagem = new javax.swing.JLabel();
        anoNasc = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblIdade.setText("Idade");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(60, 210, 260, 20);
        lblIdade.getAccessibleContext().setAccessibleName("lblIdade");

        jLabel1.setText("Ano de Nascimento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 105, 16);
        jLabel1.getAccessibleContext().setAccessibleName("lblAnoNasc");

        btnCalcular.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\pr03cauagomes\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\calculadora_icon2.png")); // NOI18N
        btnCalcular.setText("Calcular Idade");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(110, 140, 150, 30);
        btnCalcular.getAccessibleContext().setAccessibleName("btnCalcular");

        pessoaimagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\pr03cauagomes\\src\\main\\java\\br\\com\\ifba\\atividade03\\images\\imagem_pessoa_icon.png")); // NOI18N
        getContentPane().add(pessoaimagem);
        pessoaimagem.setBounds(320, 40, 320, 270);
        pessoaimagem.getAccessibleContext().setAccessibleName("lblpessoaimagem");

        getContentPane().add(anoNasc);
        anoNasc.setBounds(190, 70, 90, 30);
        anoNasc.getAccessibleContext().setAccessibleName("anoNasc");

        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 100, 0, 0);
        jLabel2.getAccessibleContext().setAccessibleName("imagempessoas");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int PegarAnoAtual(){ //funcao para retornar ano atual como inteiro
       Year AnoAtual = Year.now(); //pega o ano atual da maquina
       return AnoAtual.getValue(); // retorna como inteiro
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
          int Anonasc = (Integer) anoNasc.getValue();//valor obtido no spinner
          int anoAtual = PegarAnoAtual(); //usa a funcao pra retornar o ano atual como inteiro
          if(Anonasc > anoAtual){
          lblIdade.setText("digite uma data valida");
          }     
          if(Anonasc == anoAtual){
          lblIdade.setText("voce tem apenas alguns meses de vida");
          }
          if(Anonasc > anoAtual){
        lblIdade.setText("voce ainda nao nasceu");
            }else{
          int idade = anoAtual - Anonasc; // faz o calculo
          lblIdade.setText("Idade :" + idade + " anos");//imprime no label
          }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadorawingjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadorawingjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadorawingjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadorawingjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calculadorawingjava().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anoNasc;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel pessoaimagem;
    // End of variables declaration//GEN-END:variables
}
