/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

/**
 *
 * @author Cauã
 */
import br.com.ifba.atividade09.java.Pagamento;
import br.com.ifba.atividade09.java.PagamentoCartao;
import br.com.ifba.atividade09.java.PagamentoDinheiro;
import br.com.ifba.atividade09.java.PagamentoPix;
import javax.swing.JOptionPane;
public class TelaPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamentos
     */
    public TelaPagamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEscolha = new javax.swing.JLabel();
        lblValorProduto = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        cbEscolhaPagamento = new javax.swing.JComboBox<>();
        spValorProduto = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEscolha.setText("Escolha o tipo de pagamento :");

        lblValorProduto.setText("Valor do Produto :");

        lblResultado.setText("Resultado :");

        cbEscolhaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartao", "Pix" }));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEscolha)
                                    .addComponent(lblValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEscolhaPagamento, 0, 94, Short.MAX_VALUE)
                                    .addComponent(spValorProduto))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscolha)
                    .addComponent(cbEscolhaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spValorProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
         String tipoPagamento = (String)cbEscolhaPagamento.getSelectedItem();// pega o tipo de pagamento da comboBox e coloca numa string
         double valorCompra = (Integer)spValorProduto.getValue(); // pega um valor inteiro de um spinner
         if( valorCompra <= 0 ){ // verificacao
             JOptionPane.showMessageDialog(null,"Valor invalido","ERROR",JOptionPane.ERROR_MESSAGE);
         }else{
         Pagamento pagamento = null; // cria a variavel do tipo "Pagamento" e iniciliza com null

        switch(tipoPagamento){ // verifica de que tipo selecionado na COMBOBOX e escolhe a correta

            case "Dinheiro" ->

            pagamento = new PagamentoDinheiro(); //se for Dinheiro cria um objeto da classe PagamentoDinheiro
            case "Cartao"->

            pagamento = new PagamentoCartao();//se for Cartao cria um objeto da classe PagamentoCartao
            case "Pix" -> 
          
            pagamento = new PagamentoPix();  //se for Pix cria um objeto da classe PagamentoPix
        }

        if(pagamento!= null){ // se nao ocorrer nenhum erro

              double valorFinal = pagamento.calcularTotal(valorCompra); // criae variavel valor final e preenche usando o metodo de calcularToatal
             lblResultado.setText(pagamento.imprimirRecibo(valorCompra, valorFinal));// Imprimi o recibo no LABEL
        }
      }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbEscolhaPagamento;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JSpinner spValorProduto;
    // End of variables declaration//GEN-END:variables
}
